workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      vars:
        PACKAGE_NAME: "com.bluechip.finance"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Make gradlew executable
        script: |
          chmod +x gradlew
      - name: Build Release APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - hakanerbasss@gmail.com
